package com.example.transactionmonitoring.repository;

/**
 * Aggregate projection for the number of alerts generated by a transaction.
 */
public interface TransactionAlertCount {

    Long getTransactionId();

    Long getAlertCount();
}
