spring.application.name=transaction-monitoring

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/transaction_monitoring}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:123456}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=always

monitoring.currency.base=USD
monitoring.currency.rates.USD=1
monitoring.currency.rates.CNY=0.14
monitoring.currency.rates.EUR=1.17
